// js/systems/KeywordGenerationManager.js - SIMPLIFIED VERSION

class KeywordGenerationManager {
  constructor(gameEngine) {
    this.gameEngine = gameEngine;
    this.isInitialized = false;
    console.log(
      "🔑 Keyword Generation Manager created (keywords auto-generated by ContentManager)"
    );
  }

  // Simplified - keywords are now auto-generated by ContentManager
  async initialize() {
    if (this.isInitialized) return;

    // Keywords are already generated by ContentManager at game start
    this.isInitialized = true;
    console.log(
      "🔑 Keyword Generation Manager initialized (using ContentManager keywords)"
    );
  }

  // Get keyword for character (from ContentManager)
  getKeywordForCharacter(characterId) {
    const character = contentManager.getCharacter(characterId);
    return character?.achievement?.selectedKeyword || null;
  }

  // Check if character uses keyword system
  isCharacterUnlocked(characterId) {
    // Characters are always "unlocked" in new system - achievements handle the logic
    return true;
  }

  // Reset for new game (ContentManager handles this)
  reset() {
    this.isInitialized = false;
    console.log("🔄 Keyword system reset (new keywords will be generated)");
  }

  // Debug method
  debugShowKeywords() {
    console.log("🔍 DEBUG - Keywords from ContentManager:");
    Object.entries(contentManager.getAllCharacters()).forEach(([id, char]) => {
      if (char.achievement) {
        console.log(`  ${id}: "${char.achievement.selectedKeyword}"`);
      }
    });
  }

  getInitializationStatus() {
    return this.isInitialized;
  }
}
